name: extchange
description: A Flutter exchange rates application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  retrofit: ^4.0.1
  dio: ^5.0.3

  go_router: ^6.4.1

  lottie: ^2.3.0
  ms_undraw: ^3.1.0+3
  recase: ^4.1.0
  auto_animated: ^3.0.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^21.1.35

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.22.0
  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/animations/InvestingAnimation.json
